### PR TITLE
Add support for PHP 8.3

### PR DESCRIPTION
**Pull request by grizzm0**

### CODE REVIEW

**Comment by Ocramius** [comment]
@grizzm0 I have bad news: `phpspec/prophecy` probably needs to go here, which requires quite some work :-\

**Comment by Xerkus** [comment]
Huh. I had 8.3 releases with phpunit 9 and prophecy. It should be installable.

Edit: Nevermind. I checked and they had ignore platform entry for php 8.3

**Comment by grizzm0** [comment]
So I'll need to remove `phpspec/prophecy-phpunit` and rewrite the tests?

**Comment by Ocramius** [comment]
Something like that: doesn't seem like there's a ton of code though :thinking:

**Comment by grizzm0** [comment]
Gave it a try. Can't figure it out. 😞

**Comment by Ocramius** [comment]
@grizzm0 trying this out myself now :-)

**Review by Ocramius — COMMENTED** [review]
:ship: meanwhile

Yes, I did the last changes, and yes, some of the tests are more relaxed in requirements now, but overall good improvements

**Comment by grizzm0** [comment]
@Ocramius Thanks a lot. ❤️ This was the last package we needed for PHP 8.3.

**Pull request merged**
